"""Predefined hardware profiles similar to Genymotion's device catalog."""

from app.models import HardwareProfile

PREDEFINED_PROFILES: list[HardwareProfile] = [
    # === FLAGSHIP ===
    HardwareProfile(
        id="samsung-galaxy-s24-ultra",
        name="Samsung Galaxy S24 Ultra",
        brand="Samsung",
        category="flagship",
        x_res=1440,
        y_res=3120,
        dpi=505,
        default_ram_mb=12288,
        default_storage_gb=256,
        default_cpus=8,
        description="6.8\" QHD+ Dynamic AMOLED, Snapdragon 8 Gen 3",
        icon="smartphone",
    ),
    HardwareProfile(
        id="samsung-galaxy-s24",
        name="Samsung Galaxy S24",
        brand="Samsung",
        category="flagship",
        x_res=1080,
        y_res=2340,
        dpi=416,
        default_ram_mb=8192,
        default_storage_gb=128,
        default_cpus=4,
        description="6.2\" FHD+ Dynamic AMOLED, Exynos 2400",
        icon="smartphone",
    ),
    HardwareProfile(
        id="samsung-galaxy-s23-ultra",
        name="Samsung Galaxy S23 Ultra",
        brand="Samsung",
        category="flagship",
        x_res=1440,
        y_res=3088,
        dpi=500,
        default_ram_mb=12288,
        default_storage_gb=256,
        default_cpus=8,
        description="6.8\" QHD+ Dynamic AMOLED, Snapdragon 8 Gen 2",
        icon="smartphone",
    ),
    HardwareProfile(
        id="samsung-galaxy-s23",
        name="Samsung Galaxy S23",
        brand="Samsung",
        category="flagship",
        x_res=1080,
        y_res=2340,
        dpi=425,
        default_ram_mb=8192,
        default_storage_gb=128,
        default_cpus=4,
        description="6.1\" FHD+ Dynamic AMOLED, Snapdragon 8 Gen 2",
        icon="smartphone",
    ),
    HardwareProfile(
        id="google-pixel-9-pro-xl",
        name="Google Pixel 9 Pro XL",
        brand="Google",
        category="flagship",
        x_res=1344,
        y_res=2992,
        dpi=486,
        default_ram_mb=16384,
        default_storage_gb=256,
        default_cpus=8,
        description="6.8\" Super Actua LTPO OLED, Tensor G4",
        icon="smartphone",
    ),
    HardwareProfile(
        id="google-pixel-9-pro",
        name="Google Pixel 9 Pro",
        brand="Google",
        category="flagship",
        x_res=1280,
        y_res=2856,
        dpi=486,
        default_ram_mb=16384,
        default_storage_gb=256,
        default_cpus=8,
        description="6.3\" Super Actua LTPO OLED, Tensor G4",
        icon="smartphone",
    ),
    HardwareProfile(
        id="google-pixel-9",
        name="Google Pixel 9",
        brand="Google",
        category="flagship",
        x_res=1080,
        y_res=2424,
        dpi=422,
        default_ram_mb=12288,
        default_storage_gb=128,
        default_cpus=8,
        description="6.3\" Actua OLED, Tensor G4",
        icon="smartphone",
    ),
    HardwareProfile(
        id="google-pixel-8-pro",
        name="Google Pixel 8 Pro",
        brand="Google",
        category="flagship",
        x_res=1344,
        y_res=2992,
        dpi=489,
        default_ram_mb=12288,
        default_storage_gb=128,
        default_cpus=8,
        description="6.7\" Super Actua LTPO OLED, Tensor G3",
        icon="smartphone",
    ),
    HardwareProfile(
        id="google-pixel-8",
        name="Google Pixel 8",
        brand="Google",
        category="flagship",
        x_res=1080,
        y_res=2400,
        dpi=428,
        default_ram_mb=8192,
        default_storage_gb=128,
        default_cpus=4,
        description="6.2\" OLED, Tensor G3",
        icon="smartphone",
    ),
    HardwareProfile(
        id="oneplus-12",
        name="OnePlus 12",
        brand="OnePlus",
        category="flagship",
        x_res=1440,
        y_res=3168,
        dpi=510,
        default_ram_mb=16384,
        default_storage_gb=256,
        default_cpus=8,
        description="6.82\" QHD+ LTPO AMOLED, Snapdragon 8 Gen 3",
        icon="smartphone",
    ),
    HardwareProfile(
        id="oneplus-11",
        name="OnePlus 11",
        brand="OnePlus",
        category="flagship",
        x_res=1440,
        y_res=3216,
        dpi=525,
        default_ram_mb=16384,
        default_storage_gb=256,
        default_cpus=8,
        description="6.7\" QHD+ LTPO3 AMOLED, Snapdragon 8 Gen 2",
        icon="smartphone",
    ),
    HardwareProfile(
        id="xiaomi-14-pro",
        name="Xiaomi 14 Pro",
        brand="Xiaomi",
        category="flagship",
        x_res=1440,
        y_res=3200,
        dpi=521,
        default_ram_mb=16384,
        default_storage_gb=256,
        default_cpus=8,
        description="6.73\" QHD+ LTPO AMOLED, Snapdragon 8 Gen 3",
        icon="smartphone",
    ),
    HardwareProfile(
        id="sony-xperia-1-vi",
        name="Sony Xperia 1 VI",
        brand="Sony",
        category="flagship",
        x_res=1080,
        y_res=2340,
        dpi=402,
        default_ram_mb=12288,
        default_storage_gb=256,
        default_cpus=8,
        description="6.5\" FHD+ OLED, Snapdragon 8 Gen 3",
        icon="smartphone",
    ),
    # === MID-RANGE ===
    HardwareProfile(
        id="samsung-galaxy-a55",
        name="Samsung Galaxy A55",
        brand="Samsung",
        category="mid-range",
        x_res=1080,
        y_res=2340,
        dpi=403,
        default_ram_mb=8192,
        default_storage_gb=128,
        default_cpus=4,
        description="6.6\" FHD+ Super AMOLED, Exynos 1480",
        icon="smartphone",
    ),
    HardwareProfile(
        id="samsung-galaxy-a54",
        name="Samsung Galaxy A54",
        brand="Samsung",
        category="mid-range",
        x_res=1080,
        y_res=2340,
        dpi=403,
        default_ram_mb=6144,
        default_storage_gb=128,
        default_cpus=4,
        description="6.4\" FHD+ Super AMOLED, Exynos 1380",
        icon="smartphone",
    ),
    HardwareProfile(
        id="samsung-galaxy-a35",
        name="Samsung Galaxy A35",
        brand="Samsung",
        category="mid-range",
        x_res=1080,
        y_res=2340,
        dpi=403,
        default_ram_mb=6144,
        default_storage_gb=128,
        default_cpus=4,
        description="6.6\" FHD+ Super AMOLED, Exynos 1380",
        icon="smartphone",
    ),
    HardwareProfile(
        id="google-pixel-8a",
        name="Google Pixel 8a",
        brand="Google",
        category="mid-range",
        x_res=1080,
        y_res=2400,
        dpi=430,
        default_ram_mb=8192,
        default_storage_gb=128,
        default_cpus=4,
        description="6.1\" OLED, Tensor G3",
        icon="smartphone",
    ),
    HardwareProfile(
        id="google-pixel-7a",
        name="Google Pixel 7a",
        brand="Google",
        category="mid-range",
        x_res=1080,
        y_res=2400,
        dpi=429,
        default_ram_mb=8192,
        default_storage_gb=128,
        default_cpus=4,
        description="6.1\" OLED, Tensor G2",
        icon="smartphone",
    ),
    HardwareProfile(
        id="nothing-phone-2",
        name="Nothing Phone (2)",
        brand="Nothing",
        category="mid-range",
        x_res=1080,
        y_res=2412,
        dpi=394,
        default_ram_mb=12288,
        default_storage_gb=256,
        default_cpus=4,
        description="6.7\" FHD+ LTPO OLED, Snapdragon 8+ Gen 1",
        icon="smartphone",
    ),
    HardwareProfile(
        id="motorola-edge-40",
        name="Motorola Edge 40",
        brand="Motorola",
        category="mid-range",
        x_res=1080,
        y_res=2400,
        dpi=402,
        default_ram_mb=8192,
        default_storage_gb=256,
        default_cpus=4,
        description="6.55\" FHD+ pOLED, Dimensity 8020",
        icon="smartphone",
    ),
    HardwareProfile(
        id="low-end-device",
        name="Low-End Device",
        brand="Generic",
        category="mid-range",
        x_res=720,
        y_res=1280,
        dpi=280,
        default_ram_mb=2048,
        default_storage_gb=32,
        default_cpus=2,
        description="Low-spec device for compatibility testing",
        icon="smartphone",
    ),
    # === TABLETS ===
    HardwareProfile(
        id="samsung-galaxy-tab-s9-ultra",
        name="Samsung Galaxy Tab S9 Ultra",
        brand="Samsung",
        category="tablet",
        x_res=1848,
        y_res=2960,
        dpi=239,
        default_ram_mb=16384,
        default_storage_gb=512,
        default_cpus=8,
        description="14.6\" Dynamic AMOLED, Snapdragon 8 Gen 2",
        icon="tablet",
    ),
    HardwareProfile(
        id="samsung-galaxy-tab-s9",
        name="Samsung Galaxy Tab S9",
        brand="Samsung",
        category="tablet",
        x_res=1600,
        y_res=2560,
        dpi=274,
        default_ram_mb=12288,
        default_storage_gb=256,
        default_cpus=8,
        description="11\" LTPS TFT LCD, Snapdragon 8 Gen 2",
        icon="tablet",
    ),
    HardwareProfile(
        id="google-pixel-tablet",
        name="Google Pixel Tablet",
        brand="Google",
        category="tablet",
        x_res=1600,
        y_res=2560,
        dpi=276,
        default_ram_mb=8192,
        default_storage_gb=128,
        default_cpus=4,
        description="10.95\" IPS LCD, Tensor G2",
        icon="tablet",
    ),
    HardwareProfile(
        id="samsung-galaxy-tab-a9",
        name="Samsung Galaxy Tab A9+",
        brand="Samsung",
        category="tablet",
        x_res=1200,
        y_res=1920,
        dpi=210,
        default_ram_mb=4096,
        default_storage_gb=64,
        default_cpus=4,
        description="11\" TFT LCD, Snapdragon 695",
        icon="tablet",
    ),
    HardwareProfile(
        id="lenovo-tab-p12",
        name="Lenovo Tab P12",
        brand="Lenovo",
        category="tablet",
        x_res=1600,
        y_res=2560,
        dpi=267,
        default_ram_mb=8192,
        default_storage_gb=128,
        default_cpus=4,
        description="12.7\" LCD, Dimensity 7050",
        icon="tablet",
    ),
]


def get_all_profiles() -> list[HardwareProfile]:
    return PREDEFINED_PROFILES.copy()


def get_profile_by_id(profile_id: str) -> HardwareProfile | None:
    for p in PREDEFINED_PROFILES:
        if p.id == profile_id:
            return p
    return None
